### ISSUE TITLE
主题很漂亮，但是默认字体大小有点小了

### ISSUE THREAD

**Issue by Ryushane** [FishionYu/typora-inside-theme#2]
![image.png](https://i.loli.net/2020/09/08/Qh1m298nJl5KHp3.png)
目前只在Windows上试了这个主题，设置里面调字体大小似乎不起作用，默认大小有些费眼。

**Comment by HanryYu** [comment]
是太小了吗，我计划出一个黑暗模式和大字体的，不过最近比较忙还没有空去做

**Comment by Ryushane** [comment]
> 是太小了吗，我计划出一个黑暗模式和大字体的，不过最近比较忙还没有空去做

是的，默认字体大小有些太小了，看着有些费劲。
期待黑暗模式与大字体～
另外默认页面宽度其实也可以调大一些。

**Comment by Ryushane** [comment]
今天在mac上试了一下，显示heading大小的部分超出了内容区。或许不加heading显示会更加简洁美观一些。
![image.png](https://i.loli.net/2020/09/09/goySsGJeMKXmzYZ.png)

**Comment by Ryushane** [comment]
另外您在typora官网下的Download不是连接到Release的，似乎是原地tp

**Comment by HanryYu** [comment]
官网的download等大字体版本出来之后会改一下
